# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик за окном"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/5/
Content-Type: application/json

{
  "description": "Вынес из подъезда на улицу"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor_id": 5,
  "temperature": 17.1
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/5/
Content-Type: application/json
